specVersion: 0.0.1
description: Indexer for moonriver staking
repository: git@github.com:Moehringen/moonriverindexer.git
schema: ./schema.graphql
network:
  endpoint: wss://wss.moonriver.moonbeam.network
  #endpoint: wss://moonriver.api.onfinality.io
  #dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  types:
      RoundIndex: u32
      AccountId32: H256
      AuthorId: AccountId32
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleRoundCreated
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: NewRound
