specVersion: 0.0.1
description: Indexer for moonriver staking
repository: git@github.com:Moehringen/moonriverindexer.git
schema: ./schema.graphql
network:
  endpoint: wss://wss.moonriver.moonbeam.network
  #dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  types:
      AccountId: EthereumAccountId
      Address: AccountId
      Balance: u128
      RefCount: u8
      LookupSource: AccountId
      Account: 
        nonce: u256
        balance: u128
      ExtrinsicSignature: EthereumSignature
      RoundIndex: u32
      Candidate: 
        id: AccountId
        fee: Perbill
        bond: Balance
        nominators: Vec<Bond>
        total: Balance
        state: ValidatorStatus
      Nominator: 
        nominations: Vec<Bond>
        total: Balance
      Bond: 
        owner: AccountId
        amount: Balance
      ValidatorStatus: 
        _enum: 
          Active: "Null"
          Idle: "Null"
          Leaving: RoundIndex
      TxPoolResultContent: 
        pending: HashMap<H160, HashMap<U256, PoolTransaction>>
        queued: HashMap<H160, HashMap<U256, PoolTransaction>>
      TxPoolResultInspect: 
        pending: HashMap<H160, HashMap<U256, Summary>>
        queued: HashMap<H160, HashMap<U256, Summary>>
      TxPoolResultStatus: 
        pending: U256
        queued: U256
      Summary: Bytes
      PoolTransaction: 
        hash: H256
        nonce: U256
        block_hash: Option<H256>
        block_number: Option<U256>
        from: H160
        to: Option<H160>
        value: U256
        gas_price: U256
        gas: U256
        input: Bytes
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleRoundCreated
          kind: substrate/EventHandler
          filter:
            module: parachainstaking
            method: NewRound
